---
title: "Data and analytics at Slush 2014"
subtitle: "Slush 2014 from the data science point of view"
layout: post
tags: [visualization, startups]
---

[Slush], the biggest startup conference in Northern Europe, was held last week in Helsinki. 
I participated the event second time, and here I share some highlights especially from the data science point of view. To get an idea of what the startups were offering, I made the following word cloud from the 80 most common words used in the company [descriptions]:

```{r slush14_wordcloud, echo=FALSE, message=FALSE, results='hide', fig.height=7, fig.width=9}
library("tm")
library("wordcloud")
library("SnowballC")

# The input text file was created with a simple 'select all' on page
# https://www.slush.org/companies/whos-coming/
slush14.raw <- scan("../../files/data/slush2014_companies.txt",
                    what="character", sep="\n", skip=40, n=6620)
# Extract descriptions and process a bit
desc <- slush14.raw[(which(slush14.raw=="+") -1)[-1]]
desc <- tolower(gsub("[[:punct:]]", "", desc))

# Remove plurals manually
# I tried stemming with tm-package, but the output was not sensible
desc <- gsub("apps", "app", desc)
desc <- gsub("applications", "application", desc)
desc <- gsub("companies", "company", desc)
desc <- gsub("customers", "customer", desc)
desc <- gsub("develops", "develop", desc)
desc <- gsub("devices", "device", desc)
desc <- gsub("games", "game", desc)
desc <- gsub("makes", "make", desc)
desc <- gsub("provides", "provide", desc)
desc <- gsub("services", "service", desc)
desc <- gsub("solutions", "solution", desc)
desc <- gsub("systems", "system", desc)
desc <- gsub("tools", "tool", desc)
desc <- gsub("worlds", "world", desc)

# Create the word cloud
wordcloud(desc, max.words=80, scale=c(7,1), 
          random.order=FALSE, random.color=FALSE, rot.per=0.0, 
          use.r.layout=FALSE, colors=brewer.pal(6, "Dark2"), fixed.asp=FALSE)
```

*R source code for the visualization can be found in [Github](https://github.com/ouzor/ouzor.github.com/blob/master/blog/_R/2014-12-05-slush2014-data.Rmd).*

'Mobile' and 'game' were clearly the most common words. However, there were also a lot of data and analytics -related companies, as visible in the word cloud. Some companies had exciting new data-driven solutions for a variety of problems. For example, the winner of the Slush 100 pitching competition, [Enbrite.ly], offered a tool for analyzing web site traffic and detecting fraud activity. Many companies also provided tools for making analytics more accessible. 

The popularity of data-driven services is of course not surprising with all the big data hype going on. Many of these startups want to brind analytics available for everyone with easy-to-use tools. I am not worried, though, that real statistical expertise could be replaced in the near future. In fact, I am more concerned on the quality of analytics these tools provide, as there are a lot of potential [pitfalls] when conducting data analysis with software one does not really understand. And remember that [data science can’t be point and click][ds-pointclick]! 

One interesting startup I’d like to point out is [Soma analytics] from London. They analyze the tone of phone calls to detect the stress levels of the speakers. This allows the tracking of the stress levels of all employes in a company and allows the HR people to react early to reduce stress. A very cool data-driven healthcare application with a lot of potential!

Another big trend that was visible is of course the Internet of Things and sensor technology. These are super interesting, as they will be generating a lot of data in the future, and there will be need for data scientists to analyze the masses of data and combine them with other data sources.

[Nimble Devices] provides indoor tracking with applications in search and guidance. They had installed their system in the Slush venue, allowing people to locate themselves via the official Slush app. I tried this and it seemed to work nicely, but I did not basically need it, and was also a bit concerned on the battery.

Also [Walkbase] offers indoor tracking, with focus on in-store personalization. [TreLab] offers wearable sensors that can be plugged into existing industrial devices to track their usage and functionality better. [Fourdeg] has created an intelligent thermostat that automatically adjusts room temperatures, promising energy saving up to 35%.

Slush also featured a new [Impact track] this year, bringing together highly interesting speakers from around the world who wanted to solve big societal problems in various ways. One of the most exiting presentations of the whole event was given by Stefan Heeke from [Sumall.org], a non-profit data science organization. Stefan described how they had reduced homelessness in New York by predicting evictions ahead in time and allowing the social workers to step in early enough to prevent families from losing their homes. Stefan also mentioned many other interesting non-profit organizations in a [tweet] after the event.

All in all, the event was simply spectacular, and it was great to see data-driven solutions emerging in a wide range of fields. Can’t wait for the next year!



[Slush]: http://highway.slush.org/info/slush/
[Enbrite.ly]: http://www.enbrite.ly/
[descriptions]: https://www.slush.org/companies/whos-coming/
[pitfalls]: http://www.economistinsights.com/technology-innovation/opinion/are-businesses-risk-same-statistical-pitfalls-scientists
[ds-pointclick]: http://simplystatistics.org/2014/10/09/data-science-cant-be-point-and-click/
[Soma analytics]: http://www.soma-analytics.com/
[Nimble Devices]: http://www.nimbledevices.com/
[Walkbase]: http://www.walkbase.com/
[TreLab]: http://www.trelab.fi/en/ 
[Fourdeg]: http://www.fourdeg.fi/
[Impact track]: http://highway.slush.org/impact/
[Sumall.org]: http://www.sumall.org/
[tweet]: https://twitter.com/Stefan_Heeke/status/535420378475429888

